<h3><?php _e('Email Settings', 'wp_event_booking');?></h3>
<div>
<h3><?php _e('Email Template Settings', 'wp_event_booking');?></h3>
<?php do_action('wpeb_before_email_doc');?>
<p><code><?php _e('Event sign up - Admin notification Subject', 'wp_event_booking');?></code> - <?php _e('Here you can set email subject for admin notification email when customer sign up.', 'wp_event_booking');?>(<?php _e('Possible shortcodes :', 'wp_event_booking');?> %event_title%, %event_date_time%, %event_price%, %event_location% )</p>
<p><code><?php _e('Event sign up - Admin notification Body', 'wp_event_booking');?></code> - <?php _e('Here you can set email content for admin notification email when customer sign up.', 'wp_event_booking');?>(<?php _e('Possible shortcodes :', 'wp_event_booking');?> %event_title%, %event_title%, %event_date_time%, %event_price%,%event_location%, %user_details%)</p>
<hr/>
<p><code><?php _e('Event sign up - Customer notification Subject', 'wp_event_booking');?></code> - <?php _e('Here you can set email subject for customer notification email when they sign up.', 'wp_event_booking');?>(<?php _e('Possible shortcodes :', 'wp_event_booking');?> %event_title%, %event_date_time%, %event_price%, %event_location%, %booking_id%, %attendant_first_name%, %attendant_last_name%, %attendant_phone_number%. %attendant_e_mail_address%, %attendant_address%, %attendant_zip_code%, %attendant_city%, %attendant_state%, %company_name%, %company_address%, %company_zip_code%, %company_city%, %company_state%, %company_vat_number%, %company_contact_person%, %company_contact_person_phone_number%, %company_invoice_e_mail_address%, %company_reference%, %personal_identification_number%)</p>
<p><code><?php _e('Event sign up - Customer notification Body', 'wp_event_booking');?></code> - <?php _e('Here you can set email content for customer notification email when they sign up.', 'wp_event_booking');?>(<?php _e('Possible shortcodes :', 'wp_event_booking');?> %event_title%, %event_date_time%, %event_price%, %event_location%, %booking_id%, %attendant_first_name%, %attendant_last_name%, %attendant_phone_number%. %attendant_e_mail_address%, %attendant_address%, %attendant_zip_code%, %attendant_city%, %attendant_state%, %company_name%, %company_address%, %company_zip_code%, %company_city%, %company_state%, %company_vat_number%, %company_contact_person%, %company_contact_person_phone_number%, %company_invoice_e_mail_address%, %company_reference%, %personal_identification_number%, %credentials%)</p>
<hr/>
<p><code><?php _e('Event sign up(Dashboard) - Admin notification Subject', 'wp_event_booking');?></code> - <?php _e('Here you can set email subject for admin notification email when customer sign up by admin from dashboard.', 'wp_event_booking');?>(<?php _e('Possible shortcodes :', 'wp_event_booking');?> %event_title%, %event_date_time%, %event_price%, %event_location%  )</p>
<p><code><?php _e('Event sign up(Dashboard) - Admin notification Body', 'wp_event_booking');?></code> - <?php _e('Here you can set email content for admin notification email when customer sign up by admin from dashboard.', 'wp_event_booking');?>(<?php _e('Possible shortcodes :', 'wp_event_booking');?> %event_title%, %event_title%, %event_date_time%, %event_price%,%event_location%, %user_details%)</p>
<hr/>
<p><code><?php _e('Event sign up(Dashboard) - Customer notification Subject', 'wp_event_booking');?></code> - <?php _e('Here you can set email subject for customer notification email when customer sign up by admin from dashboard.', 'wp_event_booking');?>(<?php _e('Possible shortcodes :', 'wp_event_booking');?> %event_title%, %event_date_time%, %event_price%, %event_location%, %booking_id%, %attendant_first_name%, %attendant_last_name%, %attendant_phone_number%. %attendant_e_mail_address%, %attendant_address%, %attendant_zip_code%, %attendant_city%, %attendant_state%, %company_name%, %company_address%, %company_zip_code%, %company_city%, %company_state%, %company_vat_number%, %company_contact_person%, %company_contact_person_phone_number%, %company_invoice_e_mail_address%, %company_reference%, %personal_identification_number% )</p>
<p><code><?php _e('Event sign up(Dashboard) - Customer notification Body', 'wp_event_booking');?></code> - <?php _e('Here you can set email content for customer notification email when customer sign up by admin from dashboard.', 'wp_event_booking');?>(<?php _e('Possible shortcodes :', 'wp_event_booking');?> %event_title%, %event_date_time%, %event_price%, %event_location%, %booking_id%, %attendant_first_name%, %attendant_last_name%, %attendant_phone_number%. %attendant_e_mail_address%, %attendant_address%, %attendant_zip_code%, %attendant_city%, %attendant_state%, %company_name%, %company_address%, %company_zip_code%, %company_city%, %company_state%, %company_vat_number%, %company_contact_person%, %company_contact_person_phone_number%, %company_invoice_e_mail_address%, %company_reference%, %personal_identification_number%, %credentials%)</p>
<hr/>
<p><code><?php _e('Admin Cancel Sign Up - Admin notification Subject', 'wp_event_booking');?></code> - <?php _e('Here you can set email subject for admin notification email when admin cancels a customer sign up.', 'wp_event_booking');?>(<?php _e('Possible shortcodes :', 'wp_event_booking');?> %event_title%, %event_date_time%, %event_price%, %event_location%, %booking_id%, %attendant_first_name%, %attendant_last_name%, %attendant_phone_number%. %attendant_e_mail_address%, %attendant_address%, %attendant_zip_code%, %attendant_city%, %attendant_state%, %company_name%, %company_address%, %company_zip_code%, %company_city%, %company_state%, %company_vat_number%, %company_contact_person%, %company_contact_person_phone_number%, %company_invoice_e_mail_address%, %company_reference%, %personal_identification_number% )</p>
<p><code><?php _e('Admin Cancel Sign Up - Admin notification Body', 'wp_event_booking');?></code> - <?php _e('Here you can set email content for admin notification email when admin cancels a customer sign up.', 'wp_event_booking');?>(<?php _e('Possible shortcodes :', 'wp_event_booking');?> %event_title%, %event_date_time%, %event_price%, %event_location%, %booking_id%, %attendant_first_name%, %attendant_last_name%, %attendant_phone_number%. %attendant_e_mail_address%, %attendant_address%, %attendant_zip_code%, %attendant_city%, %attendant_state%, %company_name%, %company_address%, %company_zip_code%, %company_city%, %company_state%, %company_vat_number%, %company_contact_person%, %company_contact_person_phone_number%, %company_invoice_e_mail_address%, %company_reference%, %personal_identification_number%)</p>
<hr/>
<p><code><?php _e('Admin Cancel Sign Up - Customer notification Subject', 'wp_event_booking');?></code> - <?php _e('Here you can set email subject for customer notification email when admin cancels a customer sign up.', 'wp_event_booking');?>(<?php _e('Possible shortcodes :', 'wp_event_booking');?> %event_title%, %event_date_time%, %event_price%, %event_location%, %booking_id%, %attendant_first_name%, %attendant_last_name%, %attendant_phone_number%. %attendant_e_mail_address%, %attendant_address%, %attendant_zip_code%, %attendant_city%, %attendant_state%, %company_name%, %company_address%, %company_zip_code%, %company_city%, %company_state%, %company_vat_number%, %company_contact_person%, %company_contact_person_phone_number%, %company_invoice_e_mail_address%, %company_reference%, %personal_identification_number% )</p>
<p><code><?php _e('Admin Cancel Sign Up - Customer notification Body', 'wp_event_booking');?></code> - <?php _e('Here you can set email content for admin notification email when admin cancels a customer sign up.', 'wp_event_booking');?>(<?php _e('Possible shortcodes :', 'wp_event_booking');?> %event_title%, %event_date_time%, %event_price%, %event_location%, %booking_id%, %attendant_first_name%, %attendant_last_name%, %attendant_phone_number%. %attendant_e_mail_address%, %attendant_address%, %attendant_zip_code%, %attendant_city%, %attendant_state%, %company_name%, %company_address%, %company_zip_code%, %company_city%, %company_state%, %company_vat_number%, %company_contact_person%, %company_contact_person_phone_number%, %company_invoice_e_mail_address%, %company_reference%, %personal_identification_number%)</p>
<hr/>
<p><code><?php _e('User Cancel Signup - Admin notification Subject', 'wp_event_booking');?></code> - <?php _e('Here you can set email subject for admin notification email when customer cancels their sign up.', 'wp_event_booking');?>(<?php _e('Possible shortcodes :', 'wp_event_booking');?> %event_title%, %event_date_time%, %event_price%, %event_location%, %event_title%, %event_date_time%, %event_price%, %event_location%, %booking_id%, %attendant_first_name%, %attendant_last_name%, %attendant_phone_number%. %attendant_e_mail_address%, %attendant_address%, %attendant_zip_code%, %attendant_city%, %attendant_state%, %company_name%, %company_address%, %company_zip_code%, %company_city%, %company_state%, %company_vat_number%, %company_contact_person%, %company_contact_person_phone_number%, %company_invoice_e_mail_address%, %company_reference%, %personal_identification_number% )</p>
<p><code><?php _e('User Cancel Signup - Admin notification Body', 'wp_event_booking');?></code> - <?php _e('Here you can set email content for admin notification email when customer cancels their sign up.', 'wp_event_booking');?>(<?php _e('Possible shortcodes :', 'wp_event_booking');?> %event_title%, %event_date_time%, %event_price%, %event_location%, %booking_id%, %attendant_first_name%, %attendant_last_name%, %attendant_phone_number%. %attendant_e_mail_address%, %attendant_address%, %attendant_zip_code%, %attendant_city%, %attendant_state%, %company_name%, %company_address%, %company_zip_code%, %company_city%, %company_state%, %company_vat_number%, %company_contact_person%, %company_contact_person_phone_number%, %company_invoice_e_mail_address%, %company_reference%, %personal_identification_number%)</p>
<hr/>
<p><code><?php _e('User Cancel Signup - Customer notification Subject', 'wp_event_booking');?></code> - <?php _e('Here you can set email subject for customer notification email when customer cancels their sign up.', 'wp_event_booking');?>(<?php _e('Possible shortcodes :', 'wp_event_booking');?> %event_title%, %event_date_time%, %event_price%, %event_location%, %booking_id%, %attendant_first_name%, %attendant_last_name%, %attendant_phone_number%. %attendant_e_mail_address%, %attendant_address%, %attendant_zip_code%, %attendant_city%, %attendant_state%, %company_name%, %company_address%, %company_zip_code%, %company_city%, %company_state%, %company_vat_number%, %company_contact_person%, %company_contact_person_phone_number%, %company_invoice_e_mail_address%, %company_reference%, %personal_identification_number% )</p>
<p><code><?php _e('User Cancel Signup - Customer notification Body', 'wp_event_booking');?></code> - <?php _e('Here you can set email content for admin notification email when customer cancels their sign up.', 'wp_event_booking');?>(<?php _e('Possible shortcodes :', 'wp_event_booking');?> %event_title%, %event_date_time%, %event_price%, %event_location%, %booking_id%, %attendant_first_name%, %attendant_last_name%, %attendant_phone_number%. %attendant_e_mail_address%, %attendant_address%, %attendant_zip_code%, %attendant_city%, %attendant_state%, %company_name%, %company_address%, %company_zip_code%, %company_city%, %company_state%, %company_vat_number%, %company_contact_person%, %company_contact_person_phone_number%, %company_invoice_e_mail_address%, %company_reference%, %personal_identification_number%)</p>
<hr/>
<?php do_action('wpeb_after_email_doc');?>
</div>


